version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./phone_book_app/:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - db
      - test_db
    environment:
      APACHE_SERVER_NAME: csba
      APPLICATION_ENV: development
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      KIEKIS: 3
      KINT: "Labas"
    links:
      - db
      - test_db

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: csba_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
